### ISSUE TITLE
add licence!

### ISSUE THREAD

**Issue by lillemarius** [havarddj/tree-sitter-sage#1]
MIT, add credits from old repo, include from tree-sitter-python

**Comment by havarddj** [comment]
I've added a license now, what did you have in mind for the last part?

**Comment by lillemarius** [comment]
ah, we have to include (at least) the portion of the original lic crediting Max Blumenthal

**Comment by lillemarius** [comment]
*Brunsfeld sorry

but afaik

Copyright (..) 2024- håv & mar 
Copyright (c) 2016-2024 Max Brunsfeld
....

should suffice

**Comment by havarddj** [comment]
Coolio, lg?
